DuAnTotNghiep_Update7_1234567Aa@/AppView/Controllers/ThongKeController.cs
using AppData.ViewModels;
using AppData.ViewModels.ThongKe;
using AppView.PhanTrang;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Web.WebPages;

namespace AppView.Controllers
{
    public class ThongKeController : Controller
    {
        private readonly HttpClient _httpClient;
        public ThongKeController()
        {
            _httpClient = new HttpClient();
        }
      
        #region Thống Kê Sản Phẩm Được Mua nhiều Theo Ngày, Tháng, Năm 
        [HttpGet]

        public async Task<IActionResult> ThongKeSP()
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeMSSanPhamBan";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeMSSanPhamTheoSoLuong>>(apiData);

            return View(ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeSPTheoThang(DateTime? ngay, DateTime? thang, DateTime? nam)
        {

            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeMSSanPhamBan";
            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeMSSanPhamTheoSoLuong>>(apiData);
            var timkiem = ChatLieus.ToList();

            if (ngay.HasValue)
            {
                timkiem = ChatLieus.Where(x => x.Ngay.Date == ngay.Value.Date && x.Ngay.Month == ngay.Value.Month && x.Ngay.Year == ngay.Value.Year).ToList();
            }
            if (thang.HasValue)
            {
                timkiem = ChatLieus.Where(x => x.Ngay.Month == thang.Value.Month && x.Ngay.Year == thang.Value.Year).ToList();
            }
            if (nam.HasValue)
            {
                timkiem = ChatLieus.Where(x => x.Ngay.Year == nam.Value.Year).ToList();
            }

            return View("ThongKeSP", timkiem);
        }
        #endregion
        #region Thông Kê Khách Hàng Mua Nhiêù Theo Ngày, Tháng , Năm
        public int PageSize = 8;
        [HttpGet]

        public async Task<IActionResult> ThongKeKH(int ProductPage = 1)
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeKHTheoSoLuongHoaDon";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeKHMuaNhieu>>(apiData);

            return View(new PhanTrangThongKeKH
            {
                listkhs = ChatLieus
                        .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = ChatLieus.Count()
                }

            }
                );
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeSPKHTheoThang(DateTime ThangStart, DateTime ThangEnd, int ProductPage = 1)
        {

            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeKHTheoSoLuongHoaDon";
            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeKHMuaNhieu>>(apiData);
            var timkiem = ChatLieus.ToList();

            timkiem = timkiem.Where(x => x.Ngay.Month >= ThangStart.Month && x.Ngay.Month <= ThangEnd.Month).ToList();

            return View("ThongKeKH",new PhanTrangThongKeKH
            {
                listkhs = timkiem
                         .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = timkiem.Count()
                }

            }
                 );
        }
        [HttpGet]
        public async Task<IActionResult> GetAllLSTDByIDKH(Guid id,int ProductPage = 1)
        {
            //
            string apiURL = $"https://localhost:7095/api/LichSuTichDiem/GetLSTDByIdKH?idkh={id}";
            var response = await _httpClient.GetAsync(apiURL);
            var apiData = await response.Content.ReadAsStringAsync();
            var roles = JsonConvert.DeserializeObject<List<LichSuTichDiemView>>(apiData);
            return View(new PhanTrangLSTD
            {
                listLSTDs = roles
                        .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = roles.Count()
                }

            }
                );

        }
        #endregion
        #region Thông Kê Doanh Thu  Theo Ngày, Tháng , Năm
        [HttpGet]
        public async Task<IActionResult> ThongKeDoanhThuTheoNgay()
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeDoanhThuTheoNgay";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);

            return View(ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> LocThongKeDoanhThuTheoNgay(DateTime NgayStart,DateTime NgayEnd)
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeDoanhThuTheoNgay";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);
            var timkiem = ChatLieus.ToList();
            timkiem=timkiem.Where(x=>x.Ngay.Date>=NgayStart.Date&&x.Ngay.Date<=NgayEnd.Date).ToList();
            return View("ThongKeDoanhThuTheoNgay", timkiem);
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeDoanhThuTheoThang()
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeDoanhThuTheoThang";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);

            return View(ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> LocThongKeDoanhThuTheoThang(DateTime NgayStart, DateTime NgayEnd)
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeDoanhThuTheoThang";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);
            var timkiem = ChatLieus.ToList();
            timkiem = timkiem.Where(x => x.Ngay.Month >= NgayStart.Month && x.Ngay.Month<= NgayEnd.Month).ToList();

            return View("ThongKeDoanhThuTheoThang", timkiem);
        }
        [HttpGet]
        public async Task<IActionResult> ThongKeDoanhThuTheoNam()
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeDoanhThuTheoNam";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);

            return View(ChatLieus);
        }
        [HttpGet]
        public async Task<IActionResult> LocThongKeDoanhThuTheoNam(DateTime NgayStart, DateTime NgayEnd)
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeDoanhThuTheoNam";

            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ChatLieus = JsonConvert.DeserializeObject<List<ThongKeDoanhThu>>(apiData);
            var timkiem = ChatLieus.ToList();
            timkiem = timkiem.Where(x => x.Ngay.Year >= NgayStart.Year && x.Ngay.Year <= NgayEnd.Year).ToList();
            return View("ThongKeDoanhThuTheoNam", timkiem);
        }
        #endregion
        #region Thống Kê Số liệu 
        [HttpGet]
        public async Task<IActionResult> ThongKe()
        {
            string apiUrl = $"https://localhost:7095/api/ThongKeView/ThongKeSLCTSPBan";
            var response = await _httpClient.GetAsync(apiUrl);
            string apiData = await response.Content.ReadAsStringAsync();
            var ThongKeSLSPBan = JsonConvert.DeserializeObject<ThongKeSLSPDaBan>(apiData);
            if (ThongKeSLSPBan != null)
            {
                ViewBag.ThongKeSLSPDaBan = ThongKeSLSPBan;
            }

            string apiUrl8 = $"https://localhost:7095/api/ThongKeView/ThongKeSLCTSPBanOffline";
            var response8 = await _httpClient.GetAsync(apiUrl8);
            string apiData8 = await response8.Content.ReadAsStringAsync();
            var ThongKeSLSPBanOffline = JsonConvert.DeserializeObject<ThongKeSLSPDaBan>(apiData8);
            if (ThongKeSLSPBanOffline != null)
            {
                ViewBag.ThongKeSLSPDaBanOffline = ThongKeSLSPBanOffline;
            }


            string apiUrl1 = $"https://localhost:7095/api/ThongKeView/ThongKeSLCTSP";

            var response1 = await _httpClient.GetAsync(apiUrl1);
            string apiData1 = await response1.Content.ReadAsStringAsync();
            var ThongKeSLCTSP = JsonConvert.DeserializeObject<int>(apiData1);

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/ThongKe/GetAllLSTDByIDKH.cshtml
@model AppView.PhanTrang.PhanTrangLSTD
@{
    ViewData["Title"] = "GetAllLSTDByIDKH";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
    int stt = 1;
}

<h1>Lịch Sử Mua Hàng</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>
            <th>
                Ngày Tích Hoặc Tiêu Điểm
            </th>
            <th>
                Tên Khách Hàng
            </th>
            <th>
                Số Điện Thoại
            </th>
            <th>
                Số Điểm Tích Hoặc Tiêu
            </th>
            <th>
                Điểm Tích Khách Hàng
            </th>
            <th>
               Mã Hóa Đơn
            </th>
            <th>
                Trạng Thái
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.listLSTDs)
        {
            <tr>
                <td>
                    <strong style="color:black">@stt</strong>
                </td>
                <td>
                    <strong style="color:green">@item.NgayTichOrTieuDiem</strong>
                </td>
                <td>
                    <strong style="color:green">@item.TenKhachHang</strong>
                </td>
                <td>
                    <strong style="color:black">@item.SDT</strong>
                </td>
                <td>
                    <strong style="color:red">@item.SoDiemTichOrTieu</strong>
                </td>

                <td>
                    <strong style="color:green">@item.DiemTichKH</strong>
                </td>
                <td>
                    <strong style="color:green">@item.IDHoaDon</strong>
                </td>
                <td>
                    @if (item.TrangThai == 0)
                    {
                        <strong style="color:red">Hết</strong>
                    }
                    else
                    {
                        <strong style="color:green ">Còn</strong>
                    }
                </td>
               
                @{
                    stt++;
                }
            </tr>
        }
    </tbody>
</table>
<div class="col-12">
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
            @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
            {
                <li class="page-item"><a class="page-link" href="/ThongKe/GetAllLSTDByIDKH?ProductPage=@i">@i</a></li>

            }

            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/ThongKe/ThongKeDoanhThuTheoNam.cshtml
@model IEnumerable<AppData.ViewModels.ThongKe.ThongKeDoanhThu>

@{
    ViewData["Title"] = "ThongKeDoanhThuTheoNam";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
}

<h2>Thống kê Doanh Thu Theo Năm</h2>

<form method="get" asp-controller="ThongKe" asp-action="LocThongKeDoanhThuTheoNam">
    <label for="thangInput"> Bắt Đầu Từ Năm:</label>
    <input type="datetime-local" id="thangInput" name="NgayStart">
    <label for="thangInput">Kết Thúc Đến Năm: </label>
   <input type="datetime-local" id="thangInput" name="NgayEnd">
    <button type="submit">Thống Kê</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart" ></canvas>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text >labels.push('@result.Ngay.Year-@result.SoHoaDon  ');</text>
        <text>data.push('@result.DoanhThu');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Doanh Thu',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Năm -Tổng Số Đơn'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Doanh Thu'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/ThongKe/ThongKeDoanhThuTheoNgay.cshtml
@model IEnumerable<AppData.ViewModels.ThongKe.ThongKeDoanhThu>

@{
    ViewData["Title"] = "ThongKeDoanhThuTheoNgay";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
}

<h2>Thống kê Doanh Thu Theo Ngày</h2>

<form method="get" asp-controller="ThongKe" asp-action="LocThongKeDoanhThuTheoNgay">
    <label for="thangInput"> Bắt Đầu Từ Ngày:</label>
    <input type="date" id="thangInput" name="NgayStart">
    <label for="thangInput">Kết Thúc Đến Ngày: </label>
   <input type="date" id="thangInput" name="NgayEnd">
    <button type="submit">Thống Kê</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart" ></canvas>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text>labels.push('@result.Ngay-@result.SoHoaDon ');</text>
        <text>data.push('@result.DoanhThu');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Doanh Thu',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Ngày -Tổng Số Đơn'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Doanh Thu'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/ThongKe/ThongKeDoanhThuTheoThang.cshtml
@model IEnumerable<AppData.ViewModels.ThongKe.ThongKeDoanhThu>

@{
    ViewData["Title"] = "ThongKeDoanhThuTheoThang";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
}

<h2>Thống kê Doanh Thu Theo Tháng</h2>

<form method="get" asp-controller="ThongKe" asp-action="LocThongKeDoanhThuTheoThang">
    <label for="thangInput"> Bắt Đầu Từ Tháng:</label>
    <input type="Month" id="thangInput" name="NgayStart">
    <label for="thangInput">Kết Thúc Đến Tháng: </label>
   <input type="Month" id="thangInput" name="NgayEnd">
    <button type="submit">Thống Kê</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart" ></canvas>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text>labels.push('@result.Ngay-@result.SoHoaDon ');</text>
        <text>data.push('@result.DoanhThu');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Doanh Thu',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Tháng - Tổng Số Đơn'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Doanh Thu'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/ThongKe/ThongKeKH.cshtml
@model AppView.PhanTrang.PhanTrangThongKeKH

@{
    ViewData["Title"] = "ThongKeKH";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
    int stt = 1;
}

<h1>Thống Kê Khách Hàng</h1>
<form method="get" asp-controller="ThongKe" asp-action="ThongKeSPKHTheoThang">
    <label for="thangInput">Bắt Đầu Từ Tháng:</label>
    <input type="Month" id="thangInput" name="ThangStart">
    <label for="thangInput">Kết Thúc Đến Tháng:</label>
    <input type="month" id="thangInput" name="ThangEnd">
   
    <button type="submit">Thống Kê</button>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                STT
            </th>
           
            <th>
                Tên Khách Hàng
            </th>
            <th>
                Số Điện Thoại
            </th>
            <th>
               Email 
            </th>
            <th>
                Tổng Số Tiền
            </th>
            <th>
               Số Đơn mua
            </th>
            <th>
                Ngày Thanh Toán
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.listkhs) {
            <tr>
                <td>
               <strong style="color:black">@stt</strong>
            </td>
            
            <td>
                    <strong style="color:black">@item.Ten</strong>
            </td>
            <td>
                    <strong style="color:black">@item.SDT</strong>
            </td>
            <td>
                    <strong style="color:black">@item.Email</strong>
            </td>
                <td>
                    <strong style="color:red">@item.TongSoTien.ToString("n0") VND</strong>
                </td>
            <td>
                    <strong style="color:green">@item.SoDonMua</strong>
            </td>
            <td>
                    <strong style="color:black">@item.Ngay</strong>
            </td>
            <td>
                    <button class="btn btn-primary">
                        @Html.ActionLink("Chi tiết", "GetAllLSTDByIDKH", new { id = item.idkh }, new { @style = "color:white;" })
                    </button>
            </td>
            @{
                stt++;
            }
        </tr>
}
    </tbody>
</table>

<nav>
    <ul class="pagination justify-content-center">
        <li class="page-item disabled"><a class="page-link" href="#">Previous</span></a></li>
        @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
        {
            <li class="page-item"><a class="page-link" href="/ThongKe/ThongKeKH?ProductPage=@i">@i</a></li>

        }

        <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
</nav>
</div>

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/ThongKe/ThongKeSP.cshtml
@model IEnumerable<AppData.ViewModels.ThongKe.ThongKeMSSanPhamTheoSoLuong>

@{
    ViewData["Title"] = "ThongKeSP";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
}

<h2>Thống kê sản phẩm Bán Chạy</h2>

<form method="get" asp-controller="ThongKe" asp-action="ThongKeSPTheoThang">
    <label for="thangInput">Ngày:</label>
    <input type="date" id="thangInput" name="ngay">
    <label for="thangInput">Tháng:</label>
    <input type="month" id="thangInput" name="thang">
    <label for="thangInput">Năm:</label>
    <input type="datetime-local" id="thangInput" name="nam">
    <button type="submit">Thống Kê</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div>
    <canvas id="columnChart"  style="width:50%;height:50%"></canvas>
</div>
<div>
    <div id="columnChart1"  style="width:50%;height:50%"></div>
</div>

<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text>labels.push('@result.TenSP-@result.DoanhThu VND ');</text>
        <text>data.push('@result.SoLuong');</text>
    }

    var ctx = document.getElementById('columnChart').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Số lượng',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Tên Sản Phẩm -Doanh Thu'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Số lượng'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>
<script>
    let labels = [];
    let data = [];

    @foreach (var result in Model)
    {
        <text>labels.push('@result.TenSP-@result.DoanhThu VND ');</text>
        <text>data.push('@result.SoLuong');</text>
    }

    var ctx = document.getElementById('columnChart1').getContext('2d');
    var columnChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: labels,
            datasets: [{
                label: 'Số lượng',
                data: data,
                backgroundColor: ' #0d6efd',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 0.5
            }]
        },
        options: {
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Tên Sản Phẩm -Doanh Thu'
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Số lượng'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }
            }
        }
    });
</script>