DuAnTotNghiep_Update7_1234567Aa@/AppView/Controllers/VouchersController.cs
using AppData.Models;
using AppData.ViewModels;
using AppData.ViewModels.ThongKe;
using AppView.PhanTrang;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AppView.Controllers
{
    public class VouchersController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly AssignmentDBContext dBContext;
        public VouchersController()
        {
            _httpClient = new HttpClient();
            dBContext=new AssignmentDBContext();
        }
        public int PageSize = 8;
        // get all vocher
        [HttpGet]
        public async Task<IActionResult> GetAllVoucher(int ProductPage = 1)
        {
            string apiURL = $"https://localhost:7095/api/Voucher";
            var response = await _httpClient.GetAsync(apiURL);
            var apiData = await response.Content.ReadAsStringAsync();
            var roles = JsonConvert.DeserializeObject<List<VoucherView>>(apiData);
            return View(new PhanTrangVouchers
            {
                listvouchers = roles
                        .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = roles.Count()
                }

            }
                );

        }
        // tim kiem ten
        [HttpGet]
        public async Task<IActionResult> TimKiemTenVC(string Ten, int ProductPage = 1)
        {
            string apiURL = $"https://localhost:7095/api/Voucher";
            var response = await _httpClient.GetAsync(apiURL);
            var apiData = await response.Content.ReadAsStringAsync();
            var roles = JsonConvert.DeserializeObject<List<VoucherView>>(apiData);
            return View("GetAllVoucher", new PhanTrangVouchers
            {
                listvouchers = roles.Where(x => x.Ten.Contains(Ten.Trim()))
                        .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    ItemsPerPage = PageSize,
                    CurrentPage = ProductPage,
                    TotalItems = roles.Count()
                }

            }
                );

        }
        // create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(VoucherView voucher)
        {
            try
            {
                string apiURL = $"https://localhost:7095/api/Voucher";
                var response1 = await _httpClient.GetAsync(apiURL);
                var apiData = await response1.Content.ReadAsStringAsync();
                var roles = JsonConvert.DeserializeObject<List<VoucherView>>(apiData);

                if (voucher.SoTienCan != null || voucher.Ten != null || voucher.GiaTri != null || voucher.HinhThucGiamGia != null || voucher.TrangThai != null || voucher.NgayApDung != null || voucher.NgayKetThuc != null)
                {
                    if (voucher.SoTienCan < 0)
                    {
                        ViewData["SoTienCan"] = "Số tiền cần không được âm ";
                    }
                    if (voucher.GiaTri <= 0)
                    {
                        ViewData["GiaTri"] = "Mời bạn nhập giá trị lớn hơn 0";
                    }
                    if (voucher.SoLuong <= 0)
                    {
                        ViewData["SoLuong"] = "Mời bạn nhập số lượng lớn hơn 0";
                    }
                    if (voucher.NgayKetThuc < voucher.NgayApDung)
                    {
                        ViewData["Ngay"] = "Ngày kết thúc phải lớn hơn ngày áp dụng";
                    }
                    var timkiem = roles.FirstOrDefault(x => x.Ten == voucher.Ten.Trim());
                    if (timkiem != null)
                    {
                        ViewData["Ma"] = "Mã này đã tồn tại";
                        
                    }

                    if (voucher.HinhThucGiamGia == 1)
                    {
                        if (voucher.SoTienCan == 0)
                        {
                            if (voucher.GiaTri > 100 || voucher.GiaTri <= 0)
                            {
                                ViewData["GiaTri"] = "Giá trị từ 1 đến 100";
                                return View();
                            }
                            if (voucher.GiaTri <= 100 && voucher.GiaTri > 0)
                            {
                                if (voucher.SoTienCan >= 0 && voucher.GiaTri > 0 && voucher.SoLuong > 0 && voucher.NgayKetThuc >= voucher.NgayApDung && timkiem == null)
                                {
                                    var response = await _httpClient.PostAsJsonAsync($"https://localhost:7095/api/Voucher", voucher);
                                    if (response.IsSuccessStatusCode)
                                    {
                                        return RedirectToAction("GetAllVoucher");
                                    }
                                    return View();
                                }
                            }
                        }
                        if (voucher.SoTienCan > 0)
                        {
                            if (voucher.GiaTri <= voucher.SoTienCan)
                            {
                                if (voucher.GiaTri <= 100 && voucher.GiaTri > 0)
                                {
                                    if (voucher.SoTienCan >= 0 && voucher.GiaTri > 0 && voucher.SoLuong > 0 && voucher.NgayKetThuc >= voucher.NgayApDung && timkiem == null)
                                    {
                                        var response = await _httpClient.PostAsJsonAsync($"https://localhost:7095/api/Voucher", voucher);
                                        if (response.IsSuccessStatusCode)
                                        {
                                            return RedirectToAction("GetAllVoucher");
                                        }
                                        return View();
                                    }
                                }
                                if (voucher.GiaTri > 100 || voucher.GiaTri <= 0)
                                {
                                    ViewData["GiaTri"] = "Giá trị từ 1 đến 100";
                                    return View();
                                }

                            }
                            if (voucher.GiaTri > voucher.SoTienCan)
                            {
                                ViewData["GiaTri"] = "Giá trị phải nhỏ hơn hoặc bằng số tiền cần";
                                return View();

                            }
                        }


                    }
                    if (voucher.HinhThucGiamGia == 0)
                    {
                        if (voucher.SoTienCan == 0)
                        {
                            if (voucher.GiaTri <= 0)
                            {
                                ViewData["GiaTri"] = "Giá trị phải lớn hơn 0";
                                return View();
                            }
                            if (voucher.GiaTri > 0)
                            {
                                if (voucher.SoTienCan >= 0 && voucher.GiaTri > 0 && voucher.SoLuong > 0 && voucher.NgayKetThuc >= voucher.NgayApDung && timkiem == null)
                                {
                                    var response = await _httpClient.PostAsJsonAsync($"https://localhost:7095/api/Voucher", voucher);
                                    if (response.IsSuccessStatusCode)
                                    {
                                        return RedirectToAction("GetAllVoucher");
                                    }
                                    return View();
                                }
                            }
                        }
                        if (voucher.SoTienCan > 0)
                        {
                            if (voucher.GiaTri <= voucher.SoTienCan)
                            {
                                if (voucher.GiaTri <= 0)
                                {
                                    ViewData["GiaTri"] = "Giá trị phải lớn hơn 0";
                                    return View();
                                }
                                if (voucher.GiaTri > 0)
                                {
                                    if (voucher.SoTienCan >= 0 && voucher.GiaTri > 0 && voucher.SoLuong > 0 && voucher.NgayKetThuc >= voucher.NgayApDung && timkiem == null)
                                    {
                                        var response = await _httpClient.PostAsJsonAsync($"https://localhost:7095/api/Voucher", voucher);
                                        if (response.IsSuccessStatusCode)
                                        {
                                            return RedirectToAction("GetAllVoucher");
                                        }
                                        return View();
                                    }
                                }
                            }
                            if (voucher.GiaTri > voucher.SoTienCan)
                            {
                                ViewData["GiaTri"] = "Giá trị phải nhỏ hơn hoặc bằng số tiền cần";
                                return View();
                            }
                        }
                    }


                }

                return View();
            }
            catch
            {
                return View();
            }
           
        }
        // update
        [HttpGet]
        public IActionResult Updates(Guid id)
        {
            try
            {

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/Vouchers/Create.cshtml
@model AppData.ViewModels.VoucherView

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
}

<h1>Thêm Voucher</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form  asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label class="control-label">Mã Voucher</label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
                <span  class="text-danger">@ViewData["Ma"]</span>

            </div>
            <div class="form-group">
                <label class="control-label">Loại giảm giá</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="hinhthucgiamgia" value="1" asp-for="HinhThucGiamGia">
                    <label class="form-check-label" for="flexRadioDefault1">
                        Phần trăm
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="hinhthucgiamgia" value="0" asp-for="HinhThucGiamGia">
                    <label class="form-check-label" for="flexRadioDefault2">
                        Tiền mặt
                    </label>
                </div>
            </div>
            <span class="text-danger">@ViewData["LGG"]</span>
            <div class="form-group">
                <label class="control-label"> Số tiền cần</label>
                <input asp-for="SoTienCan" class="form-control" />
                <span  class="text-danger">@ViewData["SoTienCan"]</span>
            </div>
            
                     <div class="form-group">
                        <label class="control-label"> Giá trị</label>
                        <input asp-for="GiaTri" class="form-control" />
                <span class="text-danger">@ViewData["GiaTri"]</span>
                    </div>
           
            
            <div class="form-group">
                <label class="control-label">Ngày ap dụng</label>
                <input asp-for="NgayApDung" class="form-control" />
                <span class="text-danger">@ViewData["NgayApDung"]</span>
            </div>
            <div class="form-group">
                <label class="control-label"> Ngày kết thúc</label>
                <input asp-for="NgayKetThuc" class="form-control" />
               <span class="text-danger">@ViewData["NgayKetThuc"]</span>
                <span class="text-danger">@ViewData["Ngay"]</span>
            </div>
            <div class="form-group">
                <label class="control-label"> Số lượng</label>
                <input asp-for="SoLuong" class="form-control" />
                <span class="text-danger">@ViewData["SoLuong"]</span>
            </div>
            <div class="form-group">
                <label class="control-label">Mô tả</label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Trạng thái</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="TrangThai" value="1" asp-for="TrangThai">
                    <label class="form-check-label" for="flexRadioDefault1">
                        Sử dụng
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="TrangThai" value="0" asp-for="TrangThai">
                    <label class="form-check-label" for="flexRadioDefault2">
                        Không sử dụng
                    </label>
                </div>
            </div>
            <span class="text-danger">@ViewData["TrangThai"]</span>
            <div class="form-group">
                <input type="submit" value="Thêm Voucher" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<br />
<button class="btn btn-primary">
    <a asp-action="GetAllVoucher" style="color:white;">Quay lại</a>
</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
   

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/Vouchers/GetAllVoucher.cshtml
@model AppView.PhanTrang.PhanTrangVouchers

@{
    ViewData["Title"] = "GetAllVoucher";
    int stt = 1;
}

<h1 style="text-align:center"><b>Quản lý Voucher </b></h1>


<div class="col-8">
    <a class="btn btn-primary" asp-action="Create">Thêm mới</a>
</div>
<form asp-action="TimKiemTenVC" asp-controller="Vouchers" method="get" enctype="multipart/form-data">
    <div class="input-group">
        <input type="text" name="Ten" class="form-control" placeholder="Tìm kiếm Voucher theo mã">
        <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
                <button type="submit" class="fa fa-search"></button>
            </span>
        </div>
    </div>
</form>
<table class="table"style="margin-left: 20px">
    <thead>
        <tr>
            <th style=" background-color: darkslategray;
    color: white;">STT</th>
            <th style=" background-color: darkslategray;
    color: white;">Mã Voucher</th>
            <th style=" background-color: darkslategray;
    color: white;">Hình thức giảm giá</th>
            <th style=" background-color: darkslategray;
    color: white;">Số tiền cần</th>
            <th style=" background-color: darkslategray;
    color: white;">Giá trị</th>
            <th style=" background-color: darkslategray;
    color: white;">Ngày áp dụng</th>
            <th style=" background-color: darkslategray;
    color: white;">Ngày kết thúc</th>
            <th style=" background-color: darkslategray;
    color: white;">Số lượng</th>
            <th style=" background-color: darkslategray;
    color: white;">Mô tả</th>
            <th style=" background-color: darkslategray;
    color: white;">Tình trạng</th>
            <th style=" background-color: darkslategray;
    color: white;">Trạng thái </th>
            <th style=" background-color: darkslategray;
    color: white;"> </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.listvouchers)
        {
            <tr>
                <td>
                    <strong style="color:black">@stt</strong>
                </td>

                <td>
                    @item.Ten
                </td>
                <td>
                    @if(item.HinhThucGiamGia==0){
                        <div style="color:red">Giảm Theo Tiền Mặt</div>
                    }
                    else{
                        <div style="color:green">Giảm Theo Phần Trăm</div>
                    }
                   
                </td>
                <td>
                    <div style="color:green">@item.SoTienCan.ToString("n0") VND</div>
                </td>
                <td>
                    @if (item.HinhThucGiamGia == 0)
                    {
                        <div style="color:red">@item.GiaTri.ToString("n0") VND</div>
                    }
                    else
                    {
                        <div style="color:green">@item.GiaTri %</div>
                    }
                </td>
                <td>
                    <div style="color:green">@item.NgayApDung</div>
                </td>
                <td>
                    @if (item.NgayKetThuc >= DateTime.Now)
                    {
                        <div style="color:green">@item.NgayKetThuc</div>
                    }
                    else
                    {
                        <div style="color:red">@item.NgayKetThuc</div>
                    }

                </td>
                <td>
                    <div style="color:red">@item.SoLuong</div>
                </td>
                <td>
                    <div style="color:black">@item.MoTa</div>
                </td>
                <td>
                    @{
                        if (item.NgayKetThuc >= DateTime.Now&&item.SoLuong>0)
                        {
                            <div style="color:green">Còn khuyến mãi</div>
                        }
                        else
                        {
                            <div style="color:red">Hết Khuyến mãi</div>
                        }
                    }

                </td>
                <td>
                    @{
                        if (item.TrangThai ==1)
                        {
                            <div style="color:green"> Sử dụng </div>
                        }
                        else
                        {
                            <div style="color:red">Không sử dụng</div>
                        }
                    }
                </td>
                <td>
                    <button class="btn btn-success">
                        @Html.ActionLink("Sửa", "Updates", new { id = item.Id }, new { @style = "color:white;" })
                    </button> 
                    @if(item.TrangThai==1){
                        <button class="btn btn-danger">
                        @Html.ActionLink("Không sử dụng", "KoSuDung", new { id = item.Id }, new { @style = "color:white;" })
                    </button>
                    }
                    else{
                        <button class="btn btn-success">
                            @Html.ActionLink("Sử dụng", "SuDung", new { id = item.Id }, new { @style = "color:white;" })
                        </button>
                    }
                    
                </td> @{
                    stt++;
                }
            </tr>
        }
    </tbody>
</table>
<div class="col-12">
    <nav>
        <ul class="pagination justify-content-center">
            
            @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
            {
                <li class="page-item"><a class="page-link" href="/Vouchers/GetAllVoucher?ProductPage=@i">@i</a></li>

            }

            
        </ul>
    </nav>
</div>

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/Vouchers/Updates.cshtml
@model AppData.ViewModels.VoucherView

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
}

<h1>Sửa Voucher</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form  asp-action="Updates" >
            <div asp-validation-summary="ModelOnly" class="text-danger" ></div>
            <div class="form-group"  hidden>
                <label class="control-label">ID Voucher</label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label class="control-label">Mã Voucher</label>
                <input asp-for="Ten"  class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label class="control-label">Loại giảm giá</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="hinhthucgiamgia" value="1" @(Model.HinhThucGiamGia== 1 ? "checked" : "")>
                    <label class="form-check-label" for="flexRadioDefault1">
                        Phần Trăm
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="hinhthucgiamgia" value="0" @(Model.HinhThucGiamGia == 0 ? "checked" : "")>
                    <label class="form-check-label" for="flexRadioDefault2">
                        Tiền Mặt
                    </label>
                </div>
            </div>*@
            

            <div class="form-group">
                <label class="control-label"> Số tiền cần</label>
                <input asp-for="SoTienCan" class="form-control" />
                <span  class="text-danger">@ViewData["SoTienCan"]</span>
            </div>
            @*@if (Model.HinhThucGiamGia == 0)
            {
                <div class="form-group">
                    <label class="control-label"> Giảm theo tiền mặt</label>
                    <input asp-for="GiaTri" class="form-control" />
                    <span class="text-danger">@ViewData["GiaTri"]</span>
                </div>
            }
            else
            {
                <div class="form-group">
                    <label class="control-label"> Giảm theo phần trăm</label>
                    <input asp-for="GiaTri" class="form-control" />
                    <span class="text-danger">@ViewData["GiaTri"]</span>
                </div>
            }*@
            <div class="form-group">
                <label class="control-label">Ngày áp dụng</label>
                <input asp-for="NgayApDung" class="form-control" />
                <span class="text-danger">@ViewData["NgayApDung"]</span>
            </div>
            <div class="form-group">
                <label class="control-label"> Ngày kết thúc</label>
                <input asp-for="NgayKetThuc" class="form-control" />
                <span class="text-danger">@ViewData["NgayKetThuc"]</span>
                <span class="text-danger">@ViewData["Ngay"]</span>
            </div>
            <div class="form-group">
                <label class="control-label"> Số lượng</label>
                <input asp-for="SoLuong" class="form-control" />
                <span class="text-danger">@ViewData["SoLuong"]</span>
            </div>
            <div class="form-group">
                <label class="control-label">Mô tả</label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Sửa Voucher" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<br />
<button class="btn btn-primary">
    <a asp-action="GetAllVoucher" style="color:white;">Quay lại</a>
</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
     @*<script>
            // JavaScript để quản lý trạng thái của radio buttons
            document.addEventListener("DOMContentLoaded", function () {
            var hinhthucgiamgia = @Model.HinhThucGiamGia;

            document.querySelector('input[name="hinhthucgiamgia"][value="' + hinhthucgiamgia + '"]').checked = true;
            });
        </script>*@