DuAnTotNghiep_Update7_1234567Aa@/AppView/Controllers/PhieuNhapController.cs
using AppData.Models;
using AppView.Helpers;
using AppView.PhanTrang;
using DocumentFormat.OpenXml.VariantTypes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net;
using System.Text;

namespace AppView.Controllers
{
    public class PhieuNhapController : Controller
    {
        private const string API_BASE_URL = "https://localhost";

        private readonly HttpClient _httpClient;
        private readonly AssignmentDBContext _dbContext;
        public int PageSize = 8;
        public PhieuNhapController()
        {
            _httpClient = new HttpClient(new HttpClientLogHelper(new HttpClientHandler()));
            _httpClient.BaseAddress = new Uri("https://localhost:7095/api/");
            _dbContext = new AssignmentDBContext();
        }

        public async Task<IActionResult> Show(int ProductPage = 1)
        {
            try
            {
                string apiUrl = $"https://localhost:7095/api/PhieuNhap/GetAll";
                var response = await _httpClient.GetAsync(apiUrl);
                string apiData = await response.Content.ReadAsStringAsync();
                var dsPhieuNhap = JsonConvert.DeserializeObject<List<PhieuNhap>>(apiData);
                return View(new PhanTrangBase<PhieuNhap>
                {
                    Items = dsPhieuNhap
                            .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        ItemsPerPage = PageSize,
                        CurrentPage = ProductPage,
                        TotalItems = dsPhieuNhap.Count()
                    }
                });
            }
            catch { return Redirect("https://localhost:5001/"); }
        }

        [HttpGet]
        public async Task<IActionResult> SearchTheoMa(string? Ma, int ProductPage = 1)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(Ma))
                {
                    ViewData["SearchError"] = "Vui lòng nhập tên để tìm kiếm";
                    return RedirectToAction("Show");
                }
                string apiUrl = $"https://localhost:7095/api/PhieuNhap/TimKiemPhieuNhap?Ma={Ma}";
                var response = await _httpClient.GetAsync(apiUrl);
                string apiData = await response.Content.ReadAsStringAsync();
                var users = JsonConvert.DeserializeObject<List<PhieuNhap>>(apiData);
                if (users.Count == 0)
                {
                    ViewData["SearchError"] = "Không tìm thấy kết quả phù hợp";
                }
                return View("Show", new PhanTrangBase<PhieuNhap>
                {
                    Items = users
                             .Skip((ProductPage - 1) * PageSize).Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        ItemsPerPage = PageSize,
                        CurrentPage = ProductPage,
                        TotalItems = users.Count()
                    }
                });
            }
            catch { return Redirect("https://localhost:5001/"); }
        }

        [HttpGet]
        public IActionResult Create()
        {
            var dsNhanVien = _dbContext.NhanViens
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,
                    Value = x.ID.ToString()
                });
            ViewBag.DSNhanVien = new SelectList(dsNhanVien, "Value", "Text");
            var dsKhoHang = _dbContext.KhoHangs
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,
                    Value = x.ID.ToString()
                });
            ViewBag.DSKhoHang = new SelectList(dsKhoHang, "Value", "Text");
            var dsNhaCungCap = _dbContext.NhaCungCaps
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,
                    Value = x.ID.ToString()
                });
            ViewBag.DSNhaCungCap = new SelectList(dsNhaCungCap, "Value", "Text");

            PhieuNhap model = new PhieuNhap();
            model.ChiTietPhieuNhaps = new List<ChiTietPhieuNhap>();
            model.ChiTietPhieuNhaps.Add(new ChiTietPhieuNhap() { 
                ID = Guid.NewGuid()
            });
            var dsSanPham = _dbContext
                .ChiTietSanPhams
                .Include(x => x.SanPham)
                .Include(x => x.MauSac)
                .Select(x => new
                {
                    ID = x.ID,
                    Ten = x.SanPham.Ten + " " + x.MauSac.Ten,
                    Gia = x.GiaBan,
                    MauSac = x.MauSac.Ten
                }).ToList();

            ViewBag.DSSanPham = new SelectList(dsSanPham, "ID", "Ten");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PhieuNhap kc)
        {
            var dsNhanVien = _dbContext.NhanViens
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,
                    Value = x.ID.ToString()
                });
            ViewBag.DSNhanVien = new SelectList(dsNhanVien, "Value", "Text");
            var dsKhoHang = _dbContext.KhoHangs
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,
                    Value = x.ID.ToString()
                });
            ViewBag.DSKhoHang = new SelectList(dsKhoHang, "Value", "Text");
            var dsNhaCungCap = _dbContext.NhaCungCaps
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,
                    Value = x.ID.ToString()
                });
            ViewBag.DSNhaCungCap = new SelectList(dsNhaCungCap, "Value", "Text");

            var dsSanPham = _dbContext
                .ChiTietSanPhams
                .Include(x => x.SanPham)
                .Include(x => x.MauSac)
                .Select(x => new
                {
                    ID = x.ID,
                    Ten = x.SanPham.Ten + " " + x.MauSac.Ten,
                    Gia = x.GiaBan,
                    MauSac = x.MauSac.Ten
                }).ToList();

            ViewBag.DSSanPham = new SelectList(dsSanPham, "ID", "Ten");

            try
            {
                if (!kc.NgayTao.HasValue)
                    kc.NgayTao = DateTime.Now;

                string apiUrl = $"https://localhost:7095/api/PhieuNhap/Create";
                var json = JsonConvert.SerializeObject(kc);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var reponsen = await _httpClient.PostAsync(apiUrl, content);
                if (reponsen.IsSuccessStatusCode)
                {
                    return RedirectToAction("Show");
                }
                else if (reponsen.StatusCode == HttpStatusCode.BadRequest)
                {
                    ViewBag.ErrorMessage = "Phiếu nhập này đã có trong danh sách";
                    return View(kc);
                }
                return View(kc);
            }
            catch
            {
                return Redirect("https://localhost:5001/");
            }
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            try
            {
                var dsNhanVien = _dbContext.NhanViens
               .Select(x => new SelectListItem()
               {
                   Text = x.Ten,
                   Value = x.ID.ToString()
               });
                ViewBag.DSNhanVien = new SelectList(dsNhanVien, "Value", "Text");
                var dsKhoHang = _dbContext.KhoHangs
                    .Select(x => new SelectListItem()
                    {
                        Text = x.Ten,
                        Value = x.ID.ToString()
                    });
                ViewBag.DSKhoHang = new SelectList(dsKhoHang, "Value", "Text");
                var dsNhaCungCap = _dbContext.NhaCungCaps
                    .Select(x => new SelectListItem()
                    {
                        Text = x.Ten,
                        Value = x.ID.ToString()
                    });
                ViewBag.DSNhaCungCap = new SelectList(dsNhaCungCap, "Value", "Text");

                string apiUrl = $"https://localhost:7095/api/PhieuNhap/GetById/{id}";
                var response = _httpClient.GetAsync(apiUrl).Result;
                var apiData = response.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<PhieuNhap>(apiData);

                var dsSanPham = _dbContext
                    .ChiTietSanPhams
                    .Include(x => x.SanPham)
                    .Include(x => x.MauSac)
                    .Select(x => new
                    {
                        ID = x.ID,
                        Ten = x.SanPham.Ten + " " + x.MauSac.Ten,
                        Gia = x.GiaBan,
                        MauSac = x.MauSac.Ten
                    }).ToList();

                ViewBag.DSSanPham = new SelectList(dsSanPham, "ID", "Ten");
                return View(model);
            }
            catch (Exception ex) {
                return Redirect("https://localhost:5001/");
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, PhieuNhap nv)
        {
            var dsNhanVien = _dbContext.NhanViens
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,
                    Value = x.ID.ToString()
                });
            ViewBag.DSNhanVien = new SelectList(dsNhanVien, "Value", "Text");
            var dsKhoHang = _dbContext.KhoHangs
                .Select(x => new SelectListItem()
                {
                    Text = x.Ten,

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/PhieuNhap/Create.cshtml
@model AppData.Models.PhieuNhap

@{
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
                    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
                    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
                    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    ViewData["Title"] = "Create";
}
<h4>Thêm mới phiếu nhập</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger">
                @ViewBag.ErrorMessage
            </div>
        }
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaPN" class="control-label">Mã PN</label>
                <input asp-for="MaPN" class="form-control" autocomplete="off" />
                <div id="emptyMaPNError" class="invalid-feedback d-none">Vui lòng nhập mã phiếu nhập!</div>
            </div>
            <div class="form-group">
                <label asp-for="NgayTao" class="control-label">Ngày Tạo</label>
                <input asp-for="NgayTao" class="form-control" autocomplete="off" />
                <div id="emptyNgayTaoError" class="invalid-feedback d-none">Vui lòng chọn ngày tạo !</div>
            </div>
            <div class="form-group">
                <label asp-for="GhiChu" class="control-label">Ghi chú</label>
                <input asp-for="GhiChu" class="form-control" autocomplete="off" />
                <div id="emptyGhiChuError" class="invalid-feedback d-none">Vui lòng nhập vào ghi chú!</div>
            </div>
            <div class="form-group">
                <label asp-for="IDNhanVien" class="control-label">Nhân viên</label>
                <select asp-for="IDNhanVien" class="form-control" asp-items="@ViewBag.DSNhanVien" autocomplete="off">
                    <option value="">-- Chọn --</option>
                </select>
                <div id="emptyIDNhanVienError" class="invalid-feedback d-none">Vui lòng chọn nhân viên!</div>
            </div>
            <div class="form-group">
                <label asp-for="IDKhoHang" class="control-label">Kho Hàng</label>
                <select asp-for="IDKhoHang" class="form-control" asp-items="@ViewBag.DSKhoHang" autocomplete="off">
                    <option value="">-- Chọn --</option>
                </select>
                <div id="emptyIDKhoHangError" class="invalid-feedback d-none">Vui lòng chọn kho hàng!</div>
            </div>
            <div class="form-group">
                <label asp-for="IDNhaCungCap" class="control-label">Nhà Cung Cấp</label>
                <select asp-for="IDNhaCungCap" class="form-control" asp-items="@ViewBag.DSNhaCungCap" autocomplete="off" >
                    <option value="">-- Chọn --</option>
                </select>
                <div id="emptyIDNhaCungCapError" class="invalid-feedback d-none">Vui lòng chọn nhà cung cấp!</div>
            </div>
            <div class="col-12 ml-5">
                <table id="details" class="table table-borderless table-sm mb-0 pb-0">
                    <thead>
                        <tr>
                            <th>Tên sản phẩm</th>
                            <th>Số lượng</th>
                            <th>
                                <button id="btnAddDetailRow" type="button" class="btn btn-sm btn-secondary visible" onclick="AddItem(this)">
                                    Thêm
                                </button>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.ChiTietPhieuNhaps.Count; i++)
                        {
                            <tr>
                                <td>
                                    <select asp-for="@Model.ChiTietPhieuNhaps[i].IDCTSP" class="form-control" 
                                        asp-items="@ViewBag.DSSanPham">
                                    <option value="">-- Chọn --</option>
                                    </select>
                                    <span asp-validation-for="@Model.ChiTietPhieuNhaps[i].IDCTSP" class="text-danger"></span>
                                </td>
                                <td>
                                    <input asp-for="@Model.ChiTietPhieuNhaps[i].SoLuong" class="form-control" />
                                    <span asp-validation-for="@Model.ChiTietPhieuNhaps[i].SoLuong" class="text-danger"></span>
                                </td>
                                <td>
                                    <button id="btnRemove-@i" type="button" class="btn btn-sm btn-danger visible" onclick="DeleteItem(this)">
                                        Xoá
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" style="margin-top: 10px" />
            </div>
        </form>
    </div>
</div>

<script>
    $("input[name='MaPN']").on("input", function() {
        $(this).removeClass("is-invalid");
        $("#emptyMaPNError").text("");
    });

   

    $("form").submit(function() {

        var tenInput = $("input[name='MaPN']");
        var tenValue = tenInput.val();
        if (tenValue.trim() === "") {
            tenInput.addClass("is-invalid");
            $("#emptyMaPNError").text("Mã phiếu nhập không được bỏ trống");
            return false;
        }

        var nvInput = $("select[name='IDNhanVien'] option:selected");
        var nvValue = nvInput.val();
        if (nvValue.trim() === "") {
            nvInput.addClass("is-invalid");
            $("#emptyIDNhanVienError").text("Vui lòng chọn nhân viên");
            return false;
        }

        var khoInput = $("select[name='IDKhoHang'] option:selected");
        var khoValue = khoInput.val();
        if (khoValue.trim() === "") {
            khoInput.addClass("is-invalid");
            $("#emptyIDKhoHangError").text("Vui lòng chọn kho hàng");
            return false;
        }

        var nccInput = $("select[name='IDNhaCungCap'] option:selected");
        var nccValue = nccInput.val();
        if (nccValue.trim() === "") {
            nccInput.addClass("is-invalid");
            $("#emptyIDNhaCungCapError").text("Vui lòng chọn nhà cung cấp");
            return false;
        }

        return true;
    });
</script>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        function AddItem(btn) {
            var table;
            table = document.getElementById("details");
            var rows = table.getElementsByTagName("tr");
            var rowOuterHtml = rows[rows.length - 1].outerHTML;

            var lastRowIdx = rows.length - 2;

            var nextRowIdx = eval(lastRowIdx) + 1;

            rowOuterHtml = rowOuterHtml.replaceAll('_' + lastRowIdx + "_", "_" + nextRowIdx + "_");
            rowOuterHtml = rowOuterHtml.replaceAll('[' + lastRowIdx + "]", "[" + nextRowIdx + "]");
            rowOuterHtml = rowOuterHtml.replaceAll('-' + lastRowIdx, "-" + nextRowIdx);

            var newRow = table.insertRow();
            newRow.innerHTML = rowOuterHtml;

            var x = document.getElementsByTagName("input");

            for (var cnt = 0; cnt < x.length; cnt++) {
                if (x[cnt].type == "text" && x[cnt].id.indexOf("_" + nextRowIdx + "_") > 0)
                    x[cnt].value = '';
                else if (x[cnt].type == "number" && x[cnt].id.indexOf("_" + nextRowIdx + "_") > 0)
                    x[cnt].value = 0;
            }

             rebindValidators();
        }

        function DeleteItem(btn) {
            var table = document.getElementById("details");
            var rows = table.getElementsByTagName("tr");
            if (rows.length == 2) {
                alert("This row can't be delete");
                return;
            }
            $(btn).closest('tr').remove();
        }

         function rebindValidators() {
            var $form = $("#form");
            $form.unbind();
            $form.data('validator', null);
            $.validator.unobtrusive.parse($form);
            $form.validate($form.data('unobtrusiveValidation').options);
        }
    </script>
}

DuAnTotNghiep_Update7_1234567Aa@/AppView/Views/PhieuNhap/Show.cshtml
@using AppData.Models
@model AppView.PhanTrang.PhanTrangBase<PhieuNhap>

@{
    Layout = "~/Views/Shared/_LayoutForAdmin.cshtml";
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/nv.css">
    ViewData["Title"] = "Show";
    AppData.Models.AssignmentDBContext dBContext = new AppData.Models.AssignmentDBContext();
    int stt = 1;
    string searchData = "";
}

<h1>
    <b>Danh sách phiếu nhập</b>
</h1>
<div class="row" style=" margin: 5px">
    <div class="col-7">
        <a class="btn btn-primary" asp-action="Create">Thêm mới</a>
    </div>
    <div class="col-5">
        <form asp-action="SearchTheoMa" asp-controller="PhieuNhap" method="get" enctype="multipart/form-data" style="margin-left: 30px;text-align:end">
            <input class="tk1" type="text" name="Ma" placeholder="Tìm kiếm theo mã " autocomplete="off" />
            <input class="btn btn-primary" type="submit" value="Tìm kiếm" style="margin-bottom: 3px;" />
        </form>
    </div>
    <div id="searchErrorMessage" class="alert alert-warning" role="alert" style="display: @(ViewData["SearchError"] != null ? "block" : "none") ; margin-top: 10px; margin-left: 11px">@ViewData["SearchError"]</div>
</div>
<table class="table" style="margin-left: 20px">
    <thead style=" background-color: darkslategray">
        <tr>
            <th style=" background-color: darkslategray;
    color: white;">STT</th>
            <th style=" background-color: darkslategray;
    color: white;">Mã PN</th>
            <th style=" background-color: darkslategray;
    color: white;">Ngày Tạo</th>
            <th style=" background-color: darkslategray;
    color: white;">Ghi Chú</th>
            <th style=" background-color: darkslategray;
    color: white;">Nhân Viên</th>
            <th style=" background-color: darkslategray;
    color: white;">Kho Hàng</th>
            <th style=" background-color: darkslategray;
    color: white;">Nhà Cung Cấp</th>
            <th style=" background-color: darkslategray"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {

            <tr>
                <td>@stt</td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaPN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayTao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GhiChu)
                </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.NhanVien.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KhoHang.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NhaCungCap.Ten)
                </td>
                <td style="text-align:end">
                    <button class="btn btn-success" style="text-align:end">
                        @Html.ActionLink("Sửa", "Edit", new { id = item.ID }, new { @style = "color:white;" })
                    </button>
                    <button type="button" class="btn btn-danger">
                        @Html.ActionLink("Xoá", "Delete", new { id = item.ID }, new { @style = "color:white;" })
                    </button>
                </td>
                @{
                    stt++;
                }
            </tr>
        }
    </tbody>
</table>
<div style="display: flex; justify-content: center; margin: 0; padding: 0;">
    <button disabled="@(Model.PagingInfo.CurrentPage == 1)" style="background-color: @(Model.PagingInfo.CurrentPage == 1 ? "#f5f5f5" : "transparent"); border: 1px solid rgba(0, 0, 0, 0.2); border-radius: 0; margin: 0;">
        <a style="text-decoration: none; color: black;" href="@Url.Action("Show", new { ProductPage = 1 })">Đầu</a>
    </button>
    @if (Model.PagingInfo.CurrentPage > 1)
    {
        <button style="background-color: @(Model.PagingInfo.CurrentPage - 1 == Model.PagingInfo.CurrentPage ? "#99CCFF" : "transparent"); border: 1px solid rgba(0, 0, 0, 0.2); border-radius: 0; margin: 0;">
            <a style="text-decoration: none; color: black;" href="@Url.Action("Show", new { ProductPage = Model.PagingInfo.CurrentPage - 1 })">Trước</a>
        </button>
    }
    @for (int i = Math.Max(1, Model.PagingInfo.CurrentPage - 1); i <= Math.Min(Model.PagingInfo.TotalPages, Model.PagingInfo.CurrentPage + 1); i++)
    {
        <button style="background-color: @(i == Model.PagingInfo.CurrentPage ? "#99CCFF" : "transparent"); border: 1px solid rgba(0, 0, 0, 0.2); border-radius: 0; margin: 0;">
            <a style="text-decoration: none; color: black;" href="@Url.Action("Show", new { ProductPage = i })">@i</a>
        </button>
    }
    @if (Model.PagingInfo.CurrentPage < Model.PagingInfo.TotalPages)
    {
        <button style="background-color: @(Model.PagingInfo.CurrentPage + 1 == Model.PagingInfo.CurrentPage ? "#99CCFF" : "transparent");border: 1px solid rgba(0, 0, 0, 0.2); border-radius: 0; margin: 0;">
            <a style="text-decoration: none; color: black;" href="@Url.Action("Show", new { ProductPage = Model.PagingInfo.CurrentPage + 1 })">Tiếp</a>
        </button>
    }
    <button disabled="@(Model.PagingInfo.CurrentPage == Model.PagingInfo.TotalPages)" style="background-color: @(Model.PagingInfo.CurrentPage == Model.PagingInfo.TotalPages ? "#f5f5f5" : "transparent");border: 1px solid rgba(0, 0, 0, 0.2); border-radius: 0; margin: 0;">
        <a style="text-decoration: none; color: black;" href="@Url.Action("Show", new { ProductPage = Model.PagingInfo.TotalPages })">Cuối</a>
    </button>
</div>
<script>
    document.getElementById('searchForm').addEventListener('submit', function(event) {
        // Lấy dữ liệu tìm kiếm từ biến toàn cục
        var searchInput = document.querySelector('.tk1');
        searchData = sessionStorage.getItem('searchData');
        // Sử dụng dữ liệu tìm kiếm để thực hiện tìm kiếm
        if (!searchInput.value.trim()) {
            event.preventDefault(); // Prevent form submission if search input is empty
            document.getElementById('searchErrorMessage').style.display = 'block';
        } else {
            var url = '/PhieuNhap/SearchTheoMa?Ma=' + searchData;
            window.location.href = url;
        }
    });

    window.addEventListener('load', function(event) {
        // Lấy dữ liệu tìm kiếm từ biến toàn cục
        var searchInput = document.querySelector('.tk1');
        searchData = sessionStorage.getItem('searchData');
        // Nếu có dữ liệu tìm kiếm, thì điền dữ liệu đó vào ô tìm kiếm
        if (searchData) {
            searchInput.value = searchData;
        }
    });

    document.addEventListener('keydown', function(event) {
        // Nếu ấn backspace, thì load lại trang ban đầu
        if (event.key === 'Backspace') {
            var url = '/PhieuNhap/Show';
            window.location.href = url;
        }
    });

</script>